### ISSUE TITLE
SSLConfigure.ps1 reboot logic has bugs

### ISSUE THREAD

**Issue by nkindberg** [qinxgit/azure-ssl-configure#1]
The reboot logic in SSLConfigure.ps1 has several bugs.

1) DisableRC4 and Set-CryptoSetting must return $restart. The script expects these functions to return values, but currently they don't return anything. Or alternatively, use a reference variable for the parameter.
2) Need to assign return value of DisableRC4 to $reboot
3) In SetCipherOrder logic the script should set $reboot, not $restart

Can you please take a look?

For reference, here is an updated script [SSLConfigure.txt](https://github.com/qinxgit/azure-ssl-configure/files/252880/SSLConfigure.txt) with some fixes.

**Comment by qinxgit** [comment]
Yes, you are right. And your fix looks good. Can you create a pull request? In that way you can take the credit. :-)

**Comment by qinxgit** [comment]
resolved.
